name: Build, Scan, and Push Docker Image (Multi-Arch, Dockerfile Generated)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    outputs:
      images: ${{ steps.set_output.outputs.images }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dockerfile
        run: |
          cat > Dockerfile <<'EOF'
          FROM node:20-alpine
          WORKDIR /app
          COPY package.json package-lock.json ./
          RUN npm ci
          COPY . .
          EXPOSE 8080
          CMD ["node", "index.js"]
          EOF

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Build Docker image for ${{ matrix.arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: false
          tags: ghcr.io/matrix-node:${{ github.sha }}-${{ matrix.arch }}

      - name: Scan Docker image using Docker Scout
        uses: docker/scout-action@v1
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}-${{ matrix.arch }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USER }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          scan-type: full

      - name: Collect images for output
        id: set_output
        run: |
          echo "images=ghcr.io/${{ github.repository }}:${{ github.sha }}-amd64,ghcr.io/${{ github.repository }}:${{ github.sha }}-arm64" >> $GITHUB_OUTPUT

  push-image:
    needs: build-scan
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Dockerfile
        run: |
          cat > Dockerfile <<'EOF'
          FROM node:20-alpine
          WORKDIR /app
          COPY package.json package-lock.json ./
          RUN npm ci
          COPY . .
          EXPOSE 8080
          CMD ["node", "index.js"]
          EOF

      - name: Scan Docker image using Docker Scout
        uses: docker/scout-action@v1
        with:
          command: 'cves'
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
